baseURL = "http://example.org/"
languageCode = "en-us"
title = "Rust Club day 0"
theme = "reveal-hugo"

[markup.goldmark.renderer]
unsafe = true

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

[markup.highlight]
codeFences = true
style = "dracula"